# Generated by Django 2.2.4 on 2019-09-13 19:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('author', models.CharField(max_length=80)),
                ('comment_text', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
