# Generated by Django 2.2.4 on 2019-09-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='geom',
        ),
    ]
