# Generated by Django 2.2.4 on 2019-09-16 20:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_comment_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
