# Generated by Django 2.2.4 on 2019-09-17 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_comment_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 17, 21, 57, 54, 223439, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
