# Generated by Django 2.2.4 on 2019-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_assumption_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumption',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
