# Generated by Django 2.2.4 on 2019-10-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20191011_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumption',
            name='generation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='assumption',
            name='num_responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='generation',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='num_responses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='response', to=settings.AUTH_USER_MODEL),
        ),
    ]
