# Generated by Django 2.2.4 on 2019-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_auto_20191021_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumption',
            name='generation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='assumption',
            name='num_responses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='generation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='num_responses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='generation',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_responses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
