# Generated by Django 2.2.4 on 2019-10-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_auto_20191021_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumption',
            name='num_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='num_responses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='num_responses',
            field=models.IntegerField(default=0),
        ),
    ]
